
quant:
  method: "qat-llm"
  args:
    deepspeed: /home/xzy/LLM-Compression-Tool/quantization/onebit/ds_config.json
    stage: kd
    kd_alpha: 1.0
    kd_beta: 0
    kd_loss_scale: 0.01
    cutoff_len: 2048
    model_name_or_path: /home/xzy/Llama-2-7b-hf
    teacher_model_name_or_path: /home/xzy/Llama-2-7b-hf
    do_train: true
    dataset: alpaca_en_demo #kd_132k
    dataset_dir: /home/xzy/OneBit/data
    template: vanilla
    finetuning_type: full
    output_dir: /home/xzy/output/ckpt_llama2_7b_qatllm
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 4
    lr_scheduler_type: cosine
    warmup_steps: 500
    adam_beta1: 0.9
    adam_beta2: 0.98
    weight_decay: 0.01
    logging_steps: 1
    save_steps: 5000
    learning_rate: 2.0e-5
    num_train_epochs: 1
    plot_loss: true
    overwrite_output_dir: true
    fp16: true

save: /home/xzy/output/llama2_7b_qatllm